##

#
# Copyright XCTE Contributors
# This file is released under the zlib/libpng license, see license.txt in the
# root directory
#
# This class stores information and contents for a file generated by XCTE
class LangFile
  attr_accessor :lfName, :lfExtension, :lfContents, :indentLevel, :indentChars

  def initialize
    @indentLevel = 0
    @indentChars = '    '
    @lines = []
    @blockDelimOpen = '{'
    @blockDelimClose = '}'
  end

  def indent(count = 1)
    @indentLevel += count
  end

  def unindent(count = 1)
    @indentLevel -= count
  end

  def add(line = '')
    @lines.push(get_indent() << line)
  end

  def iadd(count = 1, line)
    @lines.push(get_indent(count) << line)
  end

  def same_line(line)
    @lines.last << get_indent() + line
  end

  def get_indent(extraIndent = 0)
    totalIndent = ''
    for i in 0..(indentLevel + extraIndent - 1)
      totalIndent += @indentChars
    end

    return totalIndent
  end

  def getContents
    outStr = ''

    @lines.each do |line|
      outStr << line << "\n"
    end
    return(outStr)
  end
end
